spring:
  application:
    name: PP2_3_1_2_SPRING_BOOT
  datasource:
    url: jdbc:mysql://localhost:3306/carowners?verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: uGV!hu3.24sdf
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8085
